name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./SampleWebApp2
#          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myresumeapp:latest
         
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
#    - name: Docker Login
#      uses: docker/login-action@v1.12.0
#      with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
#    - name: Docker Setup Buildx
#      uses: docker/setup-buildx-action@v1.6.0  
#      - name: Publish Docker



 #   - name: Image digest
 #     run: echo ${{ steps.docker_build.outputs.digest }}
